project:
  type: website
  output-dir: docs

website:
  title: "Cory Von Keith"
  description: "Personal website"
  site-url: https://coryvkeith.github.io
  repo-url: https://github.com/coryVkeith/coryvkeith.github.io
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: personal.qmd
        text: "Personal Interests"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    
editor: visual



