project:
  type: website
  output-dir: docs

website:
  title: "Cory Von Keith"
  about:
    template: jolla
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



