project:
  type: website
  output-dir: docs

website:
  title: "Cory Von Keith"
  description: "Personal website"
  
  repo-url: https://github.com/coryVkeith/coryvkeith.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



