---
title: "Research"
format:
  html:
    toc: true
    toc-title: "Contents"
    toc-location: left
    page-layout: full
---

Science does not occur in a vacuum. I have had the opportunity to collaborate and work with many researchers from many cultures and disciplines. Because of this, I have picked up a plethora of skills for my toolbox. 


### Molecular Biology Techniques:

::: columns
::: {.column width="60%"}
 
 Molecular Cloning: Restriction cloning, Gateway Cloning, Gibson Cloning
 
 Sequence Amplification: PCR, qPCR, RT-PCR, ddPCR, dsRNA amplification, *in vitro* transcription, mature miRNA RT-qPCR, 5' and 3' RACE, the list goes on...
 
 Transformation Techniques: Biolistic delivery, agrobacterium, chemical, electrotransporation
 
 Stable Transformation Organisms: *E. coli*, *A. tumefaciens*, *P. syringae*, *A. thaliana*, *G. hirsutum*
 
 Transient Transformation Organisms: *N. benthamiana*, *A. thaliana*, *E. coli*, *A. tumefaciens*, *T. cacao*, *V. vinifera*, *Piper spp.*, and *G. hirsutum*
 
 Gene/Genome editing/engineering: Cas9 and Cas12a, transposon mutagenesis, T-DNA insertions, site directed mutagenesis
 
 Sequencing: Sanger, Nanopore, and Illumina
 
 Synthetic biology: Desgin gene regulatory networks, amiRNA design, design of RNAi for disease resistance, Cas9 and Cas12a plant virus resistance, GFP tagging
 
 Microscopy: Widefield, fluorescence, and confocal
:::
:::


### Bioinformatics Techniques:

::: columns
::: {.column width="60%"}

Coding Languages: Python, Bash, and R

Computing: Local computing with GUI's, cloud computing with XSEDE and JETstream2, and remote High performance computing 


Genome assembly software: SPAdes, bowtie, bowtie2, Trinity, and BWA

Multiple sequence alignment software: MEGA, CD-HIT, MAUVE, MAFFT, MEGAN, SDT, CLUSTALW, MUSCLE

Phylogenetics: RaXML, PHYLIP, BEAST, Mr. Bayes, MEGA, Geneious, and PhyML

Sequence identification and annotation: BLAST, ORF finder, Geneious

Community Ecology: Phyloseq, Qiime

Other relevant skills: Docker containers and singularity, large data management, automation of pipelines and processes, protocols.io, dedication to reproducibility and open science 



:::
:::
